version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/backend.dockerfile
    container_name: backend_container
    volumes:
      - ./backend:/app
    ports:
      - "8010:5206"
    networks:
      - ecommerce-net


networks:
  ecommerce-net:
    external: true